// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AhamedAliHospitalTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ahamedAliHospital() {
    driver.get("https://ahmadalihospital.com/");
    driver.manage().window().setSize(new Dimension(1092, 720));
    driver.findElement(By.cssSelector(".elementor-element:nth-child(3) .aux-text-before")).click();
    js.executeScript("window.scrollTo(0,315)");
    driver.findElement(By.cssSelector(".eicon-close:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#menu-1-adc88bb > .menu-item-626 > .elementor-item")).click();
    js.executeScript("window.scrollTo(0,12)");
    js.executeScript("window.scrollTo(0,495)");
    driver.findElement(By.cssSelector(".attachment-full")).click();
    driver.findElement(By.cssSelector(".eicon-close:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".aux-attachment-id-865")).click();
    driver.findElement(By.cssSelector("#menu-1-adc88bb > .menu-item-289 > .elementor-item")).click();
    js.executeScript("window.scrollTo(0,415)");
    driver.findElement(By.cssSelector(".eicon-close:nth-child(1)")).click();
    driver.findElement(By.linkText("Today visiting consultant")).click();
    js.executeScript("window.scrollTo(0,372)");
    driver.findElement(By.cssSelector(".eicon-close:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,9)");
    js.executeScript("window.scrollTo(0,375)");
    driver.findElement(By.id("form-field-name")).click();
    driver.findElement(By.id("form-field-name")).sendKeys("hghghsd");
    driver.findElement(By.id("form-field-field_8a1c3c7")).click();
    driver.findElement(By.id("form-field-email")).click();
    driver.findElement(By.id("form-field-email")).sendKeys("bhjkh");
    driver.findElement(By.cssSelector(".elementor-field-group:nth-child(6) > .elementor-button")).click();
    driver.findElement(By.id("form-field-email")).sendKeys("bhjkh@gmail.com");
    driver.findElement(By.cssSelector(".elementor-field-group:nth-child(6) > .elementor-button")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".elementor-button-text:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".elementor-col-75 > #form-field-name")).click();
    driver.findElement(By.cssSelector(".elementor-col-75 > #form-field-name")).sendKeys("jhuy");
    driver.findElement(By.id("form-field-field_d0d6c26")).click();
    driver.findElement(By.id("form-field-field_d0d6c26")).sendKeys("6");
    driver.findElement(By.cssSelector(".elementor-col-50:nth-child(3) > #form-field-email")).click();
    driver.findElement(By.cssSelector(".elementor-col-50:nth-child(3) > #form-field-email")).sendKeys("kiuiu@gmail.com");
    driver.findElement(By.id("form-field-field_a9b726d")).click();
    driver.findElement(By.id("form-field-field_a9b726d")).sendKeys("no");
    driver.findElement(By.id("form-field-field_38ce510")).click();
    {
      WebElement dropdown = driver.findElement(By.id("form-field-field_38ce510"));
      dropdown.findElement(By.xpath("//option[. = 'DAY AFTER TOMORROW']")).click();
    }
    driver.findElement(By.cssSelector("#form-field-field_38ce510 > option:nth-child(3)")).click();
    driver.findElement(By.id("form-field-field_d6465d8")).click();
    {
      WebElement dropdown = driver.findElement(By.id("form-field-field_d6465d8"));
      dropdown.findElement(By.xpath("//option[. = 'Dr. N. Niroshan(EYE SURGEON)']")).click();
    }
    driver.findElement(By.cssSelector("#form-field-field_d6465d8 > option:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".elementor-field-group:nth-child(8) > .elementor-button > span")).click();
    driver.findElement(By.cssSelector("#elementor-popup-modal-738 .eicon-close")).click();
  }
}
